### ISSUE TITLE
[Bug]: Unable to get channel info and crash when tring to CTRL+C

### ISSUE THREAD

**Issue by Nando600** [ThioJoe/YT-Spammer-Purge#237]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to simply log in for the first time but then i got the error of "Error Getting Current User: Channel ID was not retrieved. Sometimes this happens if client_secrets file does not match user authorized with token.pickle file." i tried again and still failed and gave me another error

And when trying to CTRL+C the errors it also crashed

### Release version

2.2.6

### Steps to reproduce

For the Unable to get info
1. follow all steps as normal
2. try to log in for the first time
3. you should get the error after you click continue for the auth and it says it was completed

For the CTRL+C
1. just try to CTRL+C at any time and it should crash
2. if it doesnt then it might happens when you kinda spam it

### What platform are you seeing this problem on?

Windows

### Relevant log output

```shell
![image](https://user-images.githubusercontent.com/47673909/147500158-4621cc4e-864a-4dc7-88cd-e10a9c2b8c4a.png)
![image](https://user-images.githubusercontent.com/47673909/147500270-2b99b0e1-322f-4db9-8e3c-ffb46756849b.png)
```

**Comment by ThioJoe** [comment]
Hm well the Ctrl-C crash is just because in the Windows console, Ctrl+C actually is a command to end a running program, not copy to clipboard (unless you're in selection mode). That's why it says KeyboardInterrupt. So to copy from the console, try instead to drag to highlight, then simply right clicking copies to clipboard. Or, you might have to right click, hit 'mark' then do the same.

The other error doesn't seem so obvious though.  the error in general just means the API did not return a channel ID for some reason. Are you perhaps running the program on a brand new google account, or an account that does not actually have a YouTube channel created?

The only thing that caused this issue to happen for me personally, is that I was trying the app with multiple accounts, and therefore had multiple client_secrets.json files (I made a project with each account), and multiple token.pickle files, one for each account. And this error resulted when I had a mismatch between the token.pickle and client_secrets file for an account. Does that sound anything like what you're doing?

**Comment by Nando600** [comment]
> Or it looks like this might also happen, when selecting the account to log into, you chose the one that is the Google account's email address, which might not have a channel attached to it.

I am using a new google acc and this looked like to be the issue i still created another youtube account to that new Gmail just in case and that looks like to have solved it thanks for the quick help
