### ISSUE TITLE
Filtering: Invalid link not handled as expected.

### ISSUE THREAD

**Issue by Firecul** [ThioJoe/YT-Spammer-Purge#273]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I went to scan recent videos for a channel and accidentally entered a video link by mistake and instead of finding the channel or giving an error, it picked a seemingly random channel.
![WindowsTerminal_Windows_PowerShell](https://user-images.githubusercontent.com/34950371/147790564-329f52b8-80e7-4313-a2a1-310adc992314.png)

The channel in question should have returned [Rainman Ray's Repairs](https://www.youtube.com/channel/UC7qMMY6UJHpNakTDMz6vVXQ) if it worked in that manner. 

### Release version

v2.4.2

### Steps to reproduce

1. Copy a video link
2. Enter it into the recent videos scanning option
3. feel sad you picked the wrong link

### What platform are you seeing this problem on?

Windows

**Comment by ThioJoe** [comment]
Yea I came across that before but forgot to do something about it. Basically it happens because when looking up the channel ID to get the channel, it technically does a search for the channel ID, so when the link is the wrong type, things go wonky and YouTube will return weird stuff as results.

I'll add some checks to make sure it validates links better

**Comment by ThioJoe** [comment]
Should be fixed as of release 2.5.1
