### ISSUE TITLE
[Bug]: Exit as if it didn't found any spams

### ISSUE THREAD

**Issue by Devtorious** [ThioJoe/YT-Spammer-Purge#359]
### Duplicate Issues

- [x] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

<del>I was trying to do the 2nd option scan on another person's video, which the program found that there are spam but then it exit me out of the report or exclude menu. 
Although I see that you have mention in the print is the "Possible Cause: You're scanning someone else's video with a non-supported filter mode." but at first I were able do exclude people and then it crashes. From the 2nd time onward it pretty much always result into this and the 1st scan option doesn't scan some of the imposter channel like this one "https://www.youtube.com/channel/UCUf3UGvCo0PVCRB9_x_3ItA"</del>
The 3rd option which I manually enter the channel ID/links it also exit me out as if there weren't any spam found
**note:** that I have submit a filter feedback on the spam in question already

### Steps to reproduce

1. scan a specific video (https://www.youtube.com/watch?v=Yz_mfPbWEHY)
2. pick option 1 
3. exclude false positives and report
4. scan that specific video again
5. pick 2nd option and repeat 3. and 4.
6. exclude and got boot out 
7. rescan
8. pick 3rd option and input links/channel ID manually
9. gets boot out

### What platform are you seeing this problem on?

Windows

### Screenshots

```shell
![image](https://user-images.githubusercontent.com/62132131/148673348-119ef322-0f70-4a30-9869-f12e94fceae7.png)
```

**Comment by Kurdakov** [comment]
second option should exit if you are not channel owner or moderator (possibly it should be just excluded from menu not to confuse non owners and non moderators)

regarding crash - you might launch utility in console (just type cmd in explorer when you navigated Explorer to YTSpammerPurge folder, then YTSpammerPurge.exe in console) or in windows terminal to see what's wrong and provide log if possible.

regarding not found IDs - yes, I could confirm - it finds users, but does not allow to report, just exiting, if it was intended, author will comment.

thus I offer you remove info about option 2 as it is not available for reporting for non owners (possibly though it should be just removed (disabled) from menu from non owners),

and then what is left the bug is - not possible to report ids for non owners

and then about crash - possibly you might make a separate issue when you find where it crashes.

**Comment by Devtorious** [comment]
Ah I see so the 2nd options shouldn't be available from the non-channel owners, thanks for the info

**Comment by Kurdakov** [comment]
> Ah I see so the 2nd options shouldn't be available from the non-channel owners, thanks for the info

good, thanks

**Comment by TechStudent11** [comment]
@Devtorious if the issue is solved you can close the issue.

**Comment by Devtorious** [comment]
ah sorry!
