### ISSUE TITLE
Filtering: LOCALDATE.MONSTER Spam

### ISSUE THREAD

**Issue by Fighterbuilder** [ThioJoe/YT-Spammer-Purge#371]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/33814663/148985036-4cc49281-e539-4751-9ea9-3d69c52b2116.png)

### Video / Post Link

https://www.youtube.com/watch?v=2IEpC76MIK8

**Comment by Kurdakov** [comment]
see submission here https://github.com/ThioJoe/YT-Spam-Lists/issues/68 (which was incorrectly submitted - instead of spam domain youtube accounts were submitted - which currently has no separate list (and useless due to youtube spam accounts change their names frequently), so 
1. spam domains should be preferably submitted to https://github.com/ThioJoe/YT-Spam-Lists projects 
2. somehow https://github.com/ThioJoe/YT-Spam-Lists/issues/68 and this submission should be merged (but correctly as missed spam domain)

**Comment by KendallDoesCoding** [comment]
This just needs to be added to the list in https://github.com/ThioJoe/YT-Spam-Lists and in this repo in the next release and this should be sorted out. These are scam domains right?

**Comment by ThioJoe** [comment]
Yea I've gone and added it to the spam domain list
