### ISSUE TITLE
Filtering: non spam same name

### ISSUE THREAD

**Issue by DavidBOSS21** [ThioJoe/YT-Spammer-Purge#407]
### Filter Mode

Auto-Smart Mode

### Select the Problem

False Positive

### Spammer Example / Sample

![b00702a29266e31f95b84733aaa72a05](https://user-images.githubusercontent.com/98143144/150470489-ce560c01-1838-4825-9fb1-9c3e6bf83a0e.png)

### (Optional) Additional Info / Context

the person in question is not spamming but simply replying a lot

**Comment by ThioJoe** [comment]
It appears based on one of his comments that he "spammed" a question repeatedly by his own admission. So even though he's not a spammer per se, it explains why he got flagged. That's why i listed duplicates separately in the samples, so one can more easily look if they're actually spam and exclude them

**Comment by DavidBOSS21** [comment]
ah ok sorry i just only recently started using the program so im a bit of a noob

**Comment by DavidBOSS21** [comment]
to be fair im a bit of a noob in general since im trying to get into soldering
