### ISSUE TITLE
[Bug]: Error 403 access_denied after API login

### ISSUE THREAD

**Issue by Mentor1337** [ThioJoe/YT-Spammer-Purge#437]

**Comment by paul-omalley** [comment]
Is it common to get a 403 error for quotaExceeded on a first run of this app? I have added my account to the allowed users already but get a straight up Error 403 quotaExceeded everytime.
Looking in my dev portal shows no requests have been made today...

**Comment by Mentor1337** [comment]
@ThioJoe I didn't see it in the written guide(API Guide for exe), but of course, I watch the video and see that. :P Sorry, felt like an idiot.

@paul-omalley Go to the dev console, select your project, click OAuth Consent Screen on the left menu, and add yourself under test users. Why access isn't inherited, who knows.

**Comment by paul-omalley** [comment]
Thanks @Mentor1337 for the reply, but I have already done that.
The issue is that it is saying I have hit the API limit for the day when I've never used it before.
The Dev console shows no uses of the API but the error specifically states the quota has been exceeded.

**Comment by Mentor1337** [comment]
@paul-omalley Can you post the details from the dropdown under the access denied error? May show what is going on.

**Comment by paul-omalley** [comment]
@Mentor1337 - Please see the below:

`Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1478, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 290, in main
  File "Scripts\auth.py", line 113, in get_current_user
  File "Scripts\auth.py", line 111, in fetch_user
  File "googleapiclient\_helpers.py", line 131, in positional_wrapper
  File "googleapiclient\http.py", line 937, in execute
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/channels?part=snippet&mine=true&fields=items%2Fid%2Citems%2Fsnippet%2Ftitle&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
------------------------------------------------
Error Message: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/channels?part=snippet&mine=true&fields=items%2Fid%2Citems%2Fsnippet%2Ftitle&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
Status Code: 403
    Reason: quotaExceeded

Error: You have exceeded the YouTube API quota. To do more scanning you must wait until the quota resets.
 > There is a daily limit of 10,000 units/day, which works out to around reporting 10,000 comments/day.
 > You can check your quota by searching 'quota' in the google cloud console.
Solutions: Either wait until tomorrow, or create additional projects in the cloud console.
  > Read more about the quota limits for this app here: TJoe.io/api-limit-info

An 'HttpError' was raised. This is sometimes caused by a remote server error. See the error info above.
If this keeps happening, consider posting a bug report on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report
`

**Comment by Mentor1337** [comment]
@paul-omalley I will try to recreate it. Might sound stupid, you try creating a new project?

**Comment by paul-omalley** [comment]
@Mentor1337 -- Yeah. I actually tried it with two new projects and new API Keys, I get the same error both times.

**Comment by Firecul** [comment]
That's a strange error to get if you've never used the API even once yet. 
The only thing I can think of is maybe you selected the wrong one here in step 11? https://github.com/ThioJoe/YT-Spammer-Purge/wiki/Instructions:-Obtaining-an-API-Key#11-click-add-or-remove-scopes-then-find-the-one-that-says-authyoutubeforce-ssl-click-the-check-box-then-at-the-bottom-click-update-then-click-save-and-continue
No idea how likely that is just a guess.
