### ISSUE TITLE
[Bug]: API-Instructions-Key-Link broken in-app

### ISSUE THREAD

**Issue by ThisLimn0** [ThioJoe/YT-Spammer-Purge#470]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [X] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

In the line > For instructions on how to get an API key, visit: www.TJoe.io/api-setup

the link leads to Link Not Found
The page you were attempting to access could not be found. Please double-check the location, make any necessary corrections, and try again.

### Steps to reproduce

1. open app
2. copy link into browser
3. land on 404 page

### What platform are you seeing this problem on?

Windows (.exe file)

**Comment by rachmadaniHaryono** [comment]
https://github.com/ThioJoe/YT-Spammer-Purge/issues/426

duplicate?

also 

[> Ah crap it's because the www. It works if you just do "TJoe.io". I probably have a DNS record wrong, I'll see what I can do
](https://github.com/ThioJoe/YT-Spammer-Purge/issues/426#issuecomment-1027175805)

i want to create pr for this but thiojoe may have fix the url in future and make the pr useless

**Comment by ThioJoe** [comment]
Yea it's because of the www. I forgot to take it out in the latest release.
It's fixed as of 887460452f6834d973480e502388fb0413319c4b

**Comment by ThioJoe** [comment]
Fixed in release 2.14.3
