### ISSUE TITLE
TypeError: can only join an iterable

### ISSUE THREAD

**Issue by DinhHuy2010** [ThioJoe/YT-Spammer-Purge#755]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to scanning someone else video using regex (not support report) but then get TypeError

### Release version

2.16.6

### Steps to reproduce

1. Scan for a video (Video ID: Ez7anm42TXk)
2. Using regex 
3. When to logging -> Error. 

### What platform are you seeing this problem on?

Windows (.py script)

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\python\spam_base\YT-Spammer-Purge-2.16.6\YTSpammerPurge.py", line 1670, in <module>
    main()
  File "C:\python\spam_base\YT-Spammer-Purge-2.16.6\YTSpammerPurge.py", line 1647, in main
    continueRunning = primaryInstance(miscData)
  File "C:\python\spam_base\YT-Spammer-Purge-2.16.6\YTSpammerPurge.py", line 1243, in primaryInstance
    current, logMode, jsonSettingsDict = logging.prepare_logFile_settings(current, config, miscData, jsonSettingsDict, filtersDict, bypass)
  File "C:\python\spam_base\YT-Spammer-Purge-2.16.6\Scripts\logging.py", line 885, in prepare_logFile_settings
    write_log_heading(current, logMode, filtersDict)
  File "C:\python\spam_base\YT-Spammer-Purge-2.16.6\Scripts\logging.py", line 934, in write_log_heading
    write_func(current.logFileName, "Characters searched in Usernames and Comment Text: " + ", ".join(inputtedCommentTextFilter), logMode, 2)
TypeError: can only join an iterable
------------------------------------------------
Unknown Error - Code: X-5 occurred. This is probably my fault,
please a bug report on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report
```

### Screenshots

![Screenshot 2022-03-23 084943](https://user-images.githubusercontent.com/95196459/159606303-66065dbc-c03c-4404-8e12-d27956970867.png)

**Comment by EthanHindmarsh** [comment]
Probably because it is set to None by default, and wasn't updated anywhere
https://github.com/ThioJoe/YT-Spammer-Purge/blob/3d92b7a353d54c54fb2ca19a606982645631e2c6/YTSpammerPurge.py#L1038-L1040

Honestly, the whole logging system is in desperate need of a rewrite,

Why are two different variables pulling the same value?
https://github.com/ThioJoe/YT-Spammer-Purge/blob/3d92b7a353d54c54fb2ca19a606982645631e2c6/YTSpammerPurge.py#L1051-L1054

They get used in the same place immediately after too..
https://github.com/ThioJoe/YT-Spammer-Purge/blob/3d92b7a353d54c54fb2ca19a606982645631e2c6/YTSpammerPurge.py#L1096-L1097

It doesn't help much that `filterSettings[1]` is (almost) always None for no apparent reason, only reference to `filterSettings[1]` is in the regex filter-submode
https://github.com/ThioJoe/YT-Spammer-Purge/blob/f7fc6b351a8deb2ab30730c9b0ea8fd6e8b1282e/Scripts/prepare_modes.py#L446
https://github.com/ThioJoe/YT-Spammer-Purge/blob/3d92b7a353d54c54fb2ca19a606982645631e2c6/YTSpammerPurge.py#L1066

**Comment by DinhHuy2010** [comment]
This is inactive so closing the issue

**Comment by Firecul** [comment]
I wouldn't say inactive, just that @ThioJoe has probably been busy.

**Comment by ThioJoe** [comment]
> This is inactive so closing the issue

that's not how this works lol

**Comment by EthanHindmarsh** [comment]
> It doesn't help much that `filterSettings[1]` is (almost) always None for no apparent reason, only reference to `filterSettings[1]` is in the regex filter-submode
>https://github.com/ThioJoe/YT-Spammer-Purge/blob/f7fc6b351a8deb2ab30730c9b0ea8fd6e8b1282e/Scripts/prepare_modes.py#L446
>https://github.com/ThioJoe/YT-Spammer-Purge/blob/3d92b7a353d54c54fb2ca19a606982645631e2c6/YTSpammerPurge.py#L1066

This could actually be the issue

https://github.com/ThioJoe/YT-Spammer-Purge/blob/63eaa53167261a373a5ec6aa6177fdcc61a627db/YTSpammerPurge.py#L1065-L1066
`modes.prepare_filter_mode_regex(...)[1]` is always `None`
https://github.com/ThioJoe/YT-Spammer-Purge/blob/63eaa53167261a373a5ec6aa6177fdcc61a627db/Scripts/prepare_modes.py#L171

I've no idea why any of these prepare_xxx functions are returning `val, None`, 
Honestly, prepare_modes.py is hard to read😅
:shrug:

**Comment by ThioJoe** [comment]
Ok should be fixed with the latest commit. @EthanHindmarsh was correct, I found the same "None" problem, I wish I had read your comment first lol
