### ISSUE TITLE
My comments on YouTube channel are not staying 

### ISSUE THREAD

**Issue by Paskinaldo** [ThioJoe/YT-Spammer-Purge#849]
What is the cause?

**Comment by Firecul** [comment]
I'm going to need a lot more information and description of the problem before I can help.

**Comment by Paskinaldo** [comment]
> I'm going to need a lot more information and description of the problem before I can help. 

I just commented on a video and it got wiped out.

**Comment by Firecul** [comment]
You commented on someone else's video and it disappeared?

Not really what this repo is about tbh but the channel could have strict moderation in place or it's held for review. Either way I don't think, from your description, that this is the best place to ask. If there is something I'm missing though I'm happy to be corrected.

**Comment by Paskinaldo** [comment]
> You commented on someone else's video and it disappeared?
> 
> Not really what this repo is about tbh but the channel could have strict moderation in place or it's held for review. Either way I don't think, from your description, that this is the best place to ask. If there is something I'm missing though I'm happy to be corrected. 
 
Or is it from my writing? 
Is there any way of typing in a comment section? I would love to know more

**Comment by KendallDoesCoding** [comment]
Hey @Paskinaldo ,

Firstly, please create issues in this repo only related to the program ThioJoe build.

It's happened for me several times tho, so I don't mind answering it cause I find this very annoying, 

- The reason this happens is because the YouTube Spam Detection system is trash for comments are trash
- Maybe your comment inculded a link, and the channel owner blocked a link
- Moreover, on YouTube Spam Detection system being trash, if your comment was long, it goes into the held for review tab.
- Or, your comment had a blocked word

It's just weird, it's happened to many freaking times. just try to recomment but remove not required words, make comment 
short. 

Thanks,
Kendall Does Coding
