### ISSUE TITLE
New spam message is not detected

### ISSUE THREAD

**Issue by Michael-Lemons** [ThioJoe/YT-Spammer-Purge#916]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### (Optional) If 'Other', Enter Very Short Description

Filtering Suggestion

### Spammer Example / Sample

Alles sehr schön. Aber zuerst zusammen die Nummern 10 und 1.

### (Optional) Additional Info / Context

Porn spam. Multiple examples are posted from different accounts to the same video.

**Comment by Firecul** [comment]
A lot of porn spam is being caught already. 
Do you have any examples of this spam that isn't being caught?

**Comment by Michael-Lemons** [comment]
That text string was from spam that is not being caught. Unfortunately, I
deleted the messages before notifying you.

**Comment by Firecul** [comment]
Would I be correct in saying the full comment was the same as, if not similar to, the first screenshot in #918?

**Comment by Michael-Lemons** [comment]
Yes.

**Comment by Firecul** [comment]
Assuming that one of those URLs was in your comments it should be caught with the latest list update in https://github.com/ThioJoe/YT-Spam-Lists if you have more URLs to submit please do that there.
If you are happy with that please go ahead and close the issue here as I don't have access to that in this repo.

**Comment by ThioJoe** [comment]
Gonna just close this
