### ISSUE TITLE
Filtering: A few different bots were flagged as "Not Matched"

### ISSUE THREAD

**Issue by JMVRy** [ThioJoe/YT-Spammer-Purge#921]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

![YTSpammerPurge 2 15 0-Beta1_oThTvUBnBP](https://user-images.githubusercontent.com/77213524/191388330-d2d84dd8-dd6f-4ec3-acb3-9b3a05179cf8.png)

### Video / Post Link

https://www.youtube.com/watch?v=cElSBdJjUEw

### (Optional) Additional Info / Context

After noticing a multitude of spam comments, I ran this tool. The Auto-Smart mode looked the best, so I ran using it. As you can see from the screenshot provided, there were a multitude of bot comments that I believe should've been caught, but weren't for some reason or another. Two of said commenters blatantly wrote the n-word, and yet they were not matched.

**Comment by blahguy88** [comment]
To add to this post, here are some links to sample comments:

- https://www.youtube.com/watch?v=cElSBdJjUEw&lc=UgzZPO-UoI3c8EGnBNB4AaABAg.9gCzSiORtlQ9gD1f51q0A1
- https://www.youtube.com/watch?v=cElSBdJjUEw&lc=UgwCvZ6lPWNSwWITz0V4AaABAg.9gDOt1NBluJ9gE-OQ9nHED
- https://www.youtube.com/watch?v=cElSBdJjUEw&lc=UgxkQiywb2JW_FrY_3N4AaABAg.9gCycMWoU5o9gD1e0hO-cB
- https://www.youtube.com/watch?v=cElSBdJjUEw&lc=Ugy6nkDj1SbicR6D0754AaABAg.9gDM7yEIX4K9gE-My9A10e

**Comment by Firecul** [comment]
The "don't read" comments are caught in the latest version of the program at least.
These are the only ones not caught by v2.16.10 on my machine
![image](https://user-images.githubusercontent.com/34950371/191984023-fdb0eaee-9972-45cd-9cbb-9ef1141d9bcc.png)
It is strange those telegram ones make it through though I'll admit. Maybe because it's all one word, it appears to be standard ASCII text `Text-me-on-telegram…markiplier000` and `text_me_on_telegram...Markiplier000`

**Comment by ThioJoe** [comment]
A lot of these are too unique where it probably makes sense to just be caught by the duplicate filter. As for the telegram ones, they seem to be gone now, but I think they should be caught with the latest filters
