### ISSUE TITLE
[Bug]: Cannot download the latest beta

### ISSUE THREAD

**Issue by Wacob1** [ThioJoe/YT-Spammer-Purge#950]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

When trying to download the latest beta (2.17-Beta3) the script returns a 404 error and forces me to quit the program.

### Release version

2.16.10

### Steps to reproduce

1.  Start the script and then select option 9
2.  Select yes to download the beta version then a 404 error is returned

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Relevant log output

```shell
Error: GitHub returned a non 200 status code while trying to download newer version.
Status returned: 404
```

### Screenshots

![image](https://user-images.githubusercontent.com/99195813/196009669-ff0475bb-d7bc-4449-bd19-dbb91b17a7ee.png)

**Comment by Firecul** [comment]
> Ah there must be an issue with the updater for the python version. You can download the source code here: https://github.com/ThioJoe/YT-Spammer-Purge/archive/refs/tags/v2.17.0-Beta3.zip

From ThioJoe in https://github.com/ThioJoe/YT-Spammer-Purge/discussions/947#discussioncomment-3855721

**Comment by Wacob1** [comment]
Oh, I didn't see that when I was checking if this was bug that had already been found, thanks!

**Comment by Firecul** [comment]
No problem

**Comment by ThioJoe** [comment]
This seems to be an issue specifically when running on linux. I have no idea why it causes GitHub to return a 404 though.

However, in the [latest commit](https://github.com/ThioJoe/YT-Spammer-Purge/commit/58cc116f59b3c3a1596e2c0cb75be0a10cab860f) in the beta branch, I've change it so it will retry using an alternative download method.

If you're still having the issue try running it with the latest files from the [beta branch](https://github.com/ThioJoe/YT-Spammer-Purge/tree/2.17-Beta).

If it's still broken, post the screenshot, because the new function will at least show the URL that got sent so I can check that's at least correct.

**Comment by ThioJoe** [comment]
Hopefully should be fixed with the latest Beta7 release but let me know if not
